name: Django CI - Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build, Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file for CI
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env # Si vous voulez tester l'intégration Sentry
          echo "DJANGO_SETTINGS_MODULE=oc_lettings_site.settings" >> .env

      - name: Lint with Flake8
        run: |
          flake8 . --count --show-source --statistics

      - name: Run tests with Pytest and Coverage
        run: |
          pytest --cov=. --cov-fail-under=80 --ignore=env
